version: '3.8'

services:
  main_app:
    build: ./main_app
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/var/log/conversion_services
    depends_on:
      - pdf2txt
      - reduce_resolution
      - resize_images
      - convert_images
    networks:
      - conversion_network

  pdf2txt:
    build: ./pdf2txt
    volumes:
      - ./logs:/var/log/conversion_services
      - /tmp/conversions:/tmp/conversions
    expose:
      - "5001"
    networks:
      - conversion_network

  reduce_resolution:
    build: ./reduce_resolution
    volumes:
      - ./logs:/var/log/conversion_services
      - /tmp/conversions:/tmp/conversions
    expose:
      - "5002"
    networks:
      - conversion_network

  resize_images:
    build: ./resize_images
    volumes:
      - ./logs:/var/log/conversion_services
      - /tmp/conversions:/tmp/conversions
    expose:
      - "5003"
    networks:
      - conversion_network

  convert_images:
    build: ./convert_images
    volumes:
      - ./logs:/var/log/conversion_services
      - /tmp/conversions:/tmp/conversions
    expose:
      - "5004"
    networks:
      - conversion_network

networks:
  conversion_network:
    driver: bridge

volumes:
  logs: